apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prodcluster
  namespace: quarkuscoffeeshop-devteam2-gitops
  labels:
    app: quarkuscoffeeshop-devteam2-gitops-app
spec:
  clusterSelector:
    matchLabels:
      environment: prod