apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: stagingcluster
  namespace: acm-poc-devteam2-gitops
  labels:
    app: acm-poc-devteam2-gitops-app
spec:
  clusterSelector:
    matchLabels:
      environment: staging