apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: quarkuscoffeeshop-devteam1-gitops-app
  namespace: quarkuscoffeeshop-devteam1-gitops
  labels:
    app: quarkuscoffeeshop-devteam1-gitops-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: quarkuscoffeeshop-devteam1-gitops-app
