apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: acm-poc-devteam1-gitops
  labels:
    app: acm-poc-devteam1-gitops-app
spec:
  clusterSelector:
    matchLabels:
      environment: staging