apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: stagingcluster
  namespace: quarkuscoffeeshop-devteam3-gitops
  labels:
    app: quarkuscoffeeshop-devteam3-gitops-app
spec:
  clusterSelector:
    matchLabels:
      environment: staging